CREATE TABLE [dbo].[Funder]
(
[FUNDER_ID] [int] NOT NULL IDENTITY(1, 1),
[FunderName] [varchar] (50) COLLATE Latin1_General_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Funder] ADD CONSTRAINT [PK_Funder] PRIMARY KEY CLUSTERED  ([FUNDER_ID]) ON [PRIMARY]
GO
