SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[fn_EnhancementToModule_rst](
	@ENHANCEMENT_ID int
)
RETURNS @Module TABLE (
	[ModuleName] nvarchar(50) COLLATE Latin1_General_100_CI_AI NULL
) WITH EXECUTE AS CALLER
AS 
BEGIN

INSERT INTO @Module
SELECT m.ModuleName
	FROM EnhancementModule em
	INNER JOIN Module m
		ON em.MODULE_ID=m.MODULE_ID
WHERE em.ENHANCEMENT_ID=@ENHANCEMENT_ID
ORDER BY m.MODULE_ID

RETURN

END

GO
