SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[fn_EnhancementToKeyword_rst](
	@ENHANCEMENT_ID int
)
RETURNS @Keyword TABLE (
	[KEYWORD_ID] int NOT NULL,
	[Keyword] nvarchar(255) COLLATE Latin1_General_100_CI_AI NULL
) WITH EXECUTE AS CALLER
AS 
BEGIN

INSERT INTO @Keyword
SELECT k.KEYWORD_ID, k.Keyword
	FROM EnhancementKeyword ek
	INNER JOIN Keyword k
		ON ek.KEYWORD_ID=k.KEYWORD_ID
WHERE ek.ENHANCEMENT_ID=@ENHANCEMENT_ID
ORDER BY k.Keyword

RETURN

END
GO
